sudo: require
services:
    - docker

before_install:
    - docker build -t txtxx56/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true txtxx56/docker-react npm run test

language: generic

deploy:
    provider: elasticbeanstalk
    region: "eu-west-2"
    app: "docker-react"
    env: "Docker-dev"
    bucket_name: "elasticbeanstalk-eu-west-2-136404701295"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY