sudo: require
services:
    - docker

before_install:
    - docker build -t txtxx56/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true txtxx56/docker-react npm run test

language: generic